### ISSUE TITLE
Sotetseg's Hide White Screen is Disorienting

### ISSUE THREAD

**Issue by kevsgrove** [damencs/tob-qol#10]
Currently there is no visual indicator that the phase has changed. The scene goes from idling near the boss to the other end of the room in an instant. I suggest an option to replace the white transition screen with a black transition screen.

**Comment by leadanymind** [comment]
> 

This seems kind of monka. The point of removing the white screen is so  you can immediately start clicking for minimal tick loss. If you're going to just change the color, might as well make a separate plugin for that imo. Would just be annoying clutter.

**Comment by damencs** [comment]
I would just recommend not using the feature if you are disoriented by it.
