### ISSUE TITLE
uncapped fps issue

### ISSUE THREAD

**Issue by Piety37** [damencs/tob-qol#13]
i keep getting client crashes or screen flickering since using this plugin. when i check the runelite logs, i get errors from the instance timers, nylo and sote. i notice that it stops when i tick off the unlock fps option in gpu. 50 fps seems to be fine.

**Comment by damencs** [comment]
@Piety37 - Can you please provide the errors then? - I know that this has been common with just unlocked GPU within TOB anyways, but.. I'd be curious to see the logs.
