### ISSUE TITLE
Add visual metronome options

### ISSUE THREAD

**Issue by Puzzle-Drops** [damencs/tob-qol#15]
A visual metronome set to 5 anchored on xarpus similar to a monster hp percentage would be very helpful. 5 for xarpus, 10 for maiden, whatever the attack cycle is at p1, p2, and p3 verzik. etc. Would be very helpful. We already have a visual metronome plugin, just anchor it to each boss npc and put it to preset values.

**Comment by Puzzle-Drops** [comment]
Currently visual metronome is the only way I know to have a tick timer. Although the tob plugin has room tick timers only on entry. I would like a visual metronome over NPC Id's. To give an example here we have Xarpus. In order to scythe walk correctly I need to step back 2 ticks after his NPC ID changes (he's marked red). In this clip that happens at tick 3 so I need to step back on tick 1 during a 4 tick timer. During p3 Verzik I need a tick timer that is every 7 ticks instead of every 4.

Could also add an offset value so you wouldn't have text directly on top of HP percentage like in the clip shown. It could be as simple as the below:
NPCID:TickCounter:Offset
8,340:4:-24
8,372:4:+12
8,374:7:0

This plugin would take that list and as soon as NPC ID 8,340 spawns (xarpus) it would count a 4 tick timer on that NPC's location (not the player location). Another 4 tick timer for the 8,372 NPC ID (verzik p2) and then a 7 tick timer for 8,374 (verzik p3). Let me know what you think.

https://imgur.com/Xeka2RF

**Comment by damencs** [comment]
This would definitely be against TOS or at least heavily concern the RL Admins.
