### ISSUE TITLE
Toggle to remove Sacks+Room Edge from nylo room.

### ISSUE THREAD

**Issue by osbScuffi** [damencs/tob-qol#4]
A toggle to remove Spectator webs/sacks and the edge from the room, this makes the room look cleaner combined with the *Hide Pillar* option.
Both options could be merged into 1 or seperate, a example picture can be found [**Here**](https://i.imgur.com/eC8BCkR.png).
Thank you!

**Comment by damencs** [comment]
This was provided as a feature in v1.0.4.
